### ISSUE TITLE
Issues with POSTing an array of objects

### ISSUE THREAD

**Issue by neoncube2** [mgalante/jquery.redirect#12]
Hello,

I think I may have discovered a bug.

I have this object, which I've encoded as JSON.

``` javascript
{
  "survey":{
    "questions":[
      {
        "editUrl":"/survey/partials/textQuestion",
        "isEditing":false,
        "name":"test"
      }
    ],
    "configurationId":"FAA2A792-5EF9-4736-9AD1-FD30A587945E"
  }
}
```

When this is POSTed, it looks like the keys in the questions array are being put split into arrays. Here is what I get when I run var_dump() on the "survey" object that's posted.

``` PHP

Array
(
    [questions] => Array
        (
            [0] => Array
                (
                    [editUrl] => /survey/partials/textQuestion
                )

            [1] => Array
                (
                    [isEditing] => false
                )

            [2] => Array
                (
                    [name] => test
                )

        )

    [configurationId] => FAA2A792-5EF9-4736-9AD1-FD30A587945E
)
```

I expected "editUrl", "isEditing", and "name" to keys in the "questions" array, but they are encoded differently, which I think is a bug.

Hope this helps, and thanks for the library :)

**Comment by mgalante** [comment]
Thanks, i will review this as soon as posible.

**Comment by robashton84** [comment]
This bug still exists...is there a fix yet?

**Comment by ilysorc** [comment]
is there any development about this bug?

**Comment by neoncube2** [comment]
Hi @mgalante, can we please reopen this? I understand that my patch didn't fix the issue, but I'm pretty sure the issue still stands.

**Comment by mgalante** [comment]
@neoncube2 can you provide an example of the bug?

**Comment by mgalante** [comment]
I've just tried the original example of this bug:
``` javascript
{
  "survey":{
    "questions":[
      {
        "editUrl":"/survey/partials/textQuestion",
        "isEditing":false,
        "name":"test"
      }
    ],
    "configurationId":"FAA2A792-5EF9-4736-9AD1-FD30A587945E"
  }
}
```

And when is POSTed, it looks like this:
``` PHP
array(1) {
  ["survey"]=>
  array(2) {
    ["questions"]=>
    array(1) {
      [0]=>
      array(3) {
        ["editUrl"]=>
        string(29) "/survey/partials/textQuestion"
        ["isEditing"]=>
        string(5) "false"
        ["name"]=>
        string(4) "test"
      }
    }
    ["configurationId"]=>
    string(36) "FAA2A792-5EF9-4736-9AD1-FD30A587945E"
  }
}
```

**Comment by neoncube2** [comment]
@mgalante, sorry, I should have looked this over more closely before posting; I didn't see your commit to fix this issue. Anyway, I just ran a few test cases through, and it looks like the issue has been fixed.

Nice work! :)
