### ISSUE TITLE
$.redirect is not a function

### ISSUE THREAD

**Issue by Aditya-app-dev** [mgalante/jquery.redirect#15]
Hello,

I am using <b>redirect.js</b> and send this request:

$.redirect('details.php', {'return': 'yes'}, 'post');

but i am getting error of <b>$.redirect is not a function</b>

**Comment by mgalante** [comment]
Be sure to reference jquery.redirect.js after jquery:

```html
     <script src="jquery-XXX.js"></script>
     <script src="jquery.redirect.js"></script>
```

If this doesnt solve your problem please copy all the messages of error from your browser console.

**Comment by jgotti92** [comment]
I got the same issue.
This is the console output: 
[Error] TypeError: undefined is not a function (evaluating '$.redirect('https://testcps.corvus.hr/redirect/', { user: "johnDoe", password: "12345"})')
	(anonymous function) (final-step.html, line 52)
	j (jquery.min.js, line 2)
	fireWith (jquery.min.js, line 2)
	x (jquery.min.js, line 4)
	b (jquery.min.js, line 4)

**Comment by mgalante** [comment]
Can you upload a demo page somewhere so i can check your issue?

**Comment by mgalante** [comment]
Closing this

**Comment by iceman2894** [comment]
Same error can't get it to work

`patients.php:83 Uncaught TypeError: $.redirect is not a function
    at HTMLTableRowElement.<anonymous> (patients.php:83)
    at HTMLDocument.dispatch (jquery-3.2.1.min.js:3)
    at HTMLDocument.q.handle (jquery-3.2.1.min.js:3)`

**Comment by mgalante** [comment]
did you import jquery.redirect.js in your html? 
https://github.com/mgalante/jquery.redirect/issues/15#issuecomment-172535424

**Comment by iceman2894** [comment]
Yes Sure
tried with Jquery-3 & Jquery redirect
and with Jquery min & Jquery redirect
both gave an error

**Comment by mgalante** [comment]
Something is going wrong with your import.
Can you share your code with me?

**Comment by KodyKendall** [comment]
Same issue.

**Comment by KodyKendall** [comment]
I'd be willing to jump on a call with you to look at it if you want

**Comment by KodyKendall** [comment]
I actually figured mine out. I was loading jQuery twice on the same web page. So I'd load the first jQuery script, then jquery.redirect.js would get loaded, then it would reload jQuery, and then my custom script that was calling $.redirect() would fail. I think it's because the second jQuery load would overwrite the extended $.require() function that you wrote, so it then couldn't be found.
