### ISSUE TITLE
Target blank is not working

### ISSUE THREAD

**Issue by scussel** [mgalante/jquery.redirect#18]
hello, I'm having trouble opening a new tab with this code.

function open(){
      $.redirect(
           "http://posttestserver.com/post.php",
           { 
               user: "johnDoe", 
               password: "12345", 
               submit: "name"
           },
           "POST",
           "_blank"
      );
}

What can it be ?

**Comment by mgalante** [comment]
It could be a pop up blocker of the browser? i updated the example with the _blank parameter and the jQuery ready function

**Comment by scussel** [comment]
Sorry,
I got doing as follows,

$(".btn").click(function(){
$.redirect(
"http://posttestserver.com/post.php",
{ 
user: "johnDoe", 
password: "12345", 
submit: "name"
},
"POST",
"_blank"
);
}
});

**Comment by mgalante** [comment]
So now it works?

**Comment by scussel** [comment]
Yes, this working.
