### ISSUE TITLE
mime type mismatch

### ISSUE THREAD

**Issue by robashton84** [mgalante/jquery.redirect#29]
When I load a page in IE11 that uses jquery.redirect.js I get this error:

Script from https://raw.githubusercontent.com/mgalante/jquery.redirect/master/jquery.redirect.js was blocked due to mime type mismatch

Have you seen this before or know of a fix?

**Comment by robashton84** [comment]
Having used `type="application/javascript"` as well as `type="application/javascript"` I still get the error.  I have downloaded the file and run it from the server rather than from GitHub and the issue goes away.

**Comment by mgalante** [comment]
You can use this CDN:
https://cdn.rawgit.com/mgalante/jquery.redirect/master/jquery.redirect.js

**Comment by robashton84** [comment]
Thank you very much.  I'm still looking for a solution to #13; the construct of my array is altered significantly once parsed by function.

**Comment by mgalante** [comment]
Ok, i will try to make me some time to solve it. I ll  let you know in #13.
In case you want to fix it yourself you can send a PR. jQuery Redirect code its not complex.
