### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by vdudouyt** [mgalante/jquery.redirect#3]
Hi!

First of all, I'd thank you for creating this useful software! Could you please also consider adding a kind of license header to clarify the conditions under which we can use of it? Is it distributed under the same license as jQuery itself (namely https://jquery.org/license/)?

I understand that this sounds a bit bureaucratic, but is really important for those who'll try to make a us of.

Thank you very much!

Valentin

**Comment by onlyjob** [comment]
Actually this is not a free software since commit 134c55d5 incorrectly removes/overwrites name of the original author while there is no evidence that original program was ever released under free license. Lack of license and copyright attribution means "all rights reserved" i.e. non-free. An explicit permission to apply MIT license must be obtained from original developer Nemanja Avramovic who can be contacted through this form: http://avramovic.info/contact/

**Comment by onlyjob** [comment]
Using form I just left the following message:

> Dear Nemanja,

> Could you please confirm the licensing terms (and the years of your copyright) for the "jquery.redirect.js" that you have written?
There is a github project [1] where Miguel Galante is working on improving your work but it remains non-free until you confirm your permission to license it under the terms of the MIT [2] license or any other license of your choice.

> Thank you.

[1]: https://github.com/mgalante/jquery.redirect/issues/3
[2]: http://opensource.org/licenses/MIT

**Comment by avramovic** [comment]
Hello there,

I really don't like seeing my code being used and stripped of original copyright info.

My (original) code is licensed under CC BY-SA 4.0 License: http://creativecommons.org/licenses/by-sa/4.0/

This means everyone is allowed to:

* **Share** — copy and redistribute the material in any medium or format
* **Adapt** — remix, transform, and build upon the material for any purpose, even commercially. 

Under following conditions:

* **Attribution** — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
* **ShareAlike** — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

**Comment by mgalante** [comment]
Im Sorry @avramovic .  It is ok now? if not please send me the correct license.

**Comment by onlyjob** [comment]
@mgalante, you also need to add copyright statements like

    Copyright 2015 Full Name <email@address.org>
    Copyright      Nemanja Avramović (http://www.avramovic.info)

I hope @avramovic could clarify his copyright years...
Thanks.

**Comment by avramovic** [comment]
Uh, I work on so many things I can't remember exactly, but it's either from 2010 or 2011 up until 2013.

**Comment by mgalante** [comment]
Done, Thanks @avramovic @onlyjob

**Comment by onlyjob** [comment]
_Almost_ done, @mgalante. :)

Copyright attribution do not need words "original work", "modified work" -- the whole thing is copyrighted by all authors combined. I would also drop words "by" from statements but the biggest problem is that ranges are usually written as "2010-2013" so I'd recommend to replace ambiguous commas between copyright years with dashes (i.e. "-" minus characters) where years from-to are meant to be.
Thanks.

**Comment by mgalante** [comment]
@onlyjob thank you very much for your advices.

**Comment by onlyjob** [comment]
Glad to be of help. :) It is all good now. Thanks!
