### ISSUE TITLE
utf-8 in content-type

### ISSUE THREAD

**Issue by MehrdadHosseinNejad** [mgalante/jquery.redirect#30]
Hello 
I'm using your code and it's great !.
 but when i send Object that contains UTF-8 words(like persian words)  , params isn't sent properly because in content type we don't have charset="utf-8"  . 
do you have any solution ?
thank you ;D.

**Comment by mgalante** [comment]
thanks for the feedback, i think i can solve this.

**Comment by mgalante** [comment]
Sorry for the delay. I tried it and works correctly. 
Can you share with me an example of your bug? Maybe i can help you to solve it.
