### ISSUE TITLE
array data

### ISSUE THREAD

**Issue by bronte2k7** [mgalante/jquery.redirect#36]
How can I do this?
$.redirect("{% url "/login.php", {'id[]': [1, 2]}, 'GET');

can I transfer an object only?

**Comment by mgalante** [comment]
Sorry, I don't understand what your are trying to do. whats {% url?

**Comment by Bronte2k7** [comment]
I'm sorry for the mistake
I am want get redirect with parameters
$.redirect("url "/login.php", {'id[]': [1, 2]}, 'GET');

example.com/login.php?id=26&id=34

**Comment by albyx** [comment]
I encountered the same problem, the redirect does not allow the sending of arrays of objects in JSON, I modified the line of getInput method where is: 
`else {
                 name = parentString + "[" + name + "]";
 }`
in 
`name = parentString + "." + name`
I ask the author to check if it is correct.

**Comment by mgalante** [comment]
Can you provide an example of the data you are trying to send?

**Comment by wi-wissen** [comment]
I was facing the same issue.
In my case Line 174 was the problem:
``
else if (typeof values[propName] === 'object')
``

My passed array [is also an object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) so the function calls itself over and over again.

So I changed it to:
``
else if (typeof values[propName] === 'object' && !Array.isArray(values[propName]))
``
I am not sure if it is clever.

You are able to reproduce this issue with
``
$.redirect("/login.php", {user: "johnDoe", password: "12345"}, "POST", "_blank"); 
``
from given example

**Comment by mgalante** [comment]
Im checking it
