### ISSUE TITLE
TypeError: method.toUpperCase is not a function

### ISSUE THREAD

**Issue by angelomarsanz** [mgalante/jquery.redirect#43]
Estoy agregando un headers con un token:
`var csrfToken = <?php echo json_encode($this->request->getParam('_csrfToken')); ?>;`
`$.redirect('<?php echo Router::url(["controller" => "Users", "action" => "previo"]); ?>', {headers: {'X-CSRF-Token': csrfToken}} ,{filtro : 'Cliente'});`
Pero me muestra el error: "TypeError: method.toUpperCase is not a function" en esta línea del jquery.redirect:
`$.redirect = function (url, values, method, target, traditional) {
        method = (method && ["GET", "POST", "PUT", "DELETE"].indexOf(method.toUpperCase()) !== -1) ? method.toUpperCase() : 'POST';`

**Comment by mgalante** [comment]
It cannot be done - AFAIK...
This plugin doesnt support headers. Thats because internally it uses a html form to redirect the next page.

The only work arround is to send another value instead of a header.

**Comment by angelomarsanz** [comment]
Muchas gracias por su respuesta amigo !
