### ISSUE TITLE
Target _self doesn't work

### ISSUE THREAD

**Issue by hrnsykk** [mgalante/jquery.redirect#44]
Hi All,

Target _self doesn't work.  I don't see any issue in console.
With _blank target is working. 

`$(document).ready(function(){
    $('#userlogin').submit(function(){
		
			var captcha = $('#captcha').val();
			var randomcaptcha = '<?php echo $captcha; ?>';
		
		if(captcha == randomcaptcha){
			
			var username = $('#username').val();
			var password = $('#password').val();
	
			$.redirect("<?php echo URL ?>login/check", {username , password}, "POST"); 
		
		}else{

			$.redirect("<?php echo URL ?>login/wrong", {username , password}, "POST"); 
		
		};
    });
});`

**Comment by mgalante** [comment]
Hi! just add a `return false;` to your submit function to stop the defautl action of the browser.

```js
$('#userlogin').submit(function(){
		var captcha = $('#captcha').val();
		var randomcaptcha = '<?php echo $captcha; ?>';
	
	if(captcha == randomcaptcha){
		
		var username = $('#username').val();
		var password = $('#password').val();

		$.redirect("<?php echo URL ?>login/check", {username , password}, "POST"); 
	
	}else{

		$.redirect("<?php echo URL ?>login/wrong", {username , password}, "POST"); 
	
	};
return false;
});
```

**Comment by hrnsykk** [comment]
thanks
