### ISSUE TITLE
solved issue for django

### ISSUE THREAD

**Issue by youssef-jaber** [mgalante/jquery.redirect#46]

**Comment by youssef-jaber** [comment]
I solved the issue to integrate this library to make it work with Django Python.
I solved it by adding the scrf_token that gets written by django to the rendered html page in a hidden input field. I added to values object the item that correspond to the csrf_token needed by django as follows {csrfmiddlewaretoken: 'the encrypted value from html page'}
This is one of the wonderful libraries and a great add on to jQuery.
Thank you very much and keep up with good stuff like that.

**Comment by mgalante** [comment]
thanks!
