### ISSUE TITLE
How to post json data

### ISSUE THREAD

**Issue by DungeoN33** [mgalante/jquery.redirect#47]
Hi, Can I Post Json Data? 
`var data = '{keys:' + JSON.stringify(selectedKeys) + '}';`

**Comment by mgalante** [comment]
This plugin generates an invisible html form and then automatically submit it.  Then i think the only way sending the data is application/x-www-form-urlencoded

So i think its imposible to send a plain json data in the body. 

But you could send the json inside a property:

```javascript
var data = {keys:[1,2,3]};
$.redirect("/someWhere.php", { data: JSON.stringify(data) }); 
```
That will be serialized like this:
```
data=%7B%22keys%22%3A%5B1%2C2%2C3%5D%7D
```

And in the other side could be decoded
```php
array(1) { ["data"]=> string(16) "{"keys":[1,2,3]}" }
```

**Comment by DungeoN33** [comment]
You right. Not posible. But I solved. Just send string and parse with json parser on server side.

**Comment by mgalante** [comment]
great then
