### ISSUE TITLE
double url

### ISSUE THREAD

**Issue by haidi20** [mgalante/jquery.redirect#48]
how i want to double url ??

**Comment by mgalante** [comment]
Whats a double url?

**Comment by haidi20** [comment]
in your example.. just 1 url for redirect.. 
i want 2 url.. 
example i want to redirect google and facebook new tab..

**Comment by mgalante** [comment]
So... you need to open 2 tabs, right?

**Comment by haidi20** [comment]
yes sir..

**Comment by mgalante** [comment]
Sorry @haidi20 i made some test and i couldnt make it work. Browsers popup blocker will prevent the second url to open.
